
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ORM
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#
# Email Configuration (use Gmail for testing)
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_USERNAME}
spring.mail.password=${BREVO_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.from=${EMAIL}
spring.mail.protocol=smtp


app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000
#

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

frontend.url =${FRONTEND_URL}
backend.url =${BACKEND_URL}

cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${CLOUD_KEY}
cloudinary.api-secret=${CLOUD_SECRET}