spring.application.name=Blogs


server.port=1000

#Context path
server.servlet.context-path=/blogs/v1.0
spring.profiles.active=prod

#MySQL config (Change according to your local setup)
spring.datasource.url=jdbc:mysql://localhost:3306/VerdantVoices?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${DB_PASS}



#---------------- JPA CONFIG ----------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.username=${BREVO_USERNAME}
spring.mail.password=${BREVO_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.from=${EMAIL}


app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000




frontend.url =${FRONTEND_URL}
backend.url =${BACKEND_URL}

cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${CLOUD_KEY}
cloudinary.api-secret=${CLOUD_SECRET}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


